language: node_js
sudo: required
node_js:
- '16'
install:
- npm ci
jobs:
  include:
  - stage: Lint
    script: npm run lint
  - stage: Test
    script: npm run test && npm run coverage
  - stage: Deploy
    script: npm run build && curl -sSL https://raw.githubusercontent.com/RedHatInsights/insights-frontend-builder-common/master/src/bootstrap.sh | bash -s
  - stage: Release
    script: npm run release
env:
  global:
  - REPO="git@github.com:RedHatInsights/ocp-advisor-frontend-build"
  - REPO_DIR="ocp-advisor-frontend-build"
  - BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
  - NODE_OPTIONS="--max-old-space-size=4096 --max_old_space_size=4096"
