language: node_js
notifications:
  email: false
sudo: required
dist: focal
node_js:
  - 18
install:
  - npm ci
if: tag IS blank
jobs:
  include:
    - stage: Lint
      script: npm run build && npm run lint
    - stage: Test
      script: npm run test && npm run test:ct
      after_success: npm run coverage
    - stage: Tag
      if: (fork = false) AND (branch = master)
      script: npx semantic-release
env:
  global:
    - REPO="git@github.com:RedHatInsights/ocp-advisor-frontend-build"
    - REPO_DIR="ocp-advisor-frontend-build"
    - BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
